# TestRail 轉換器快速配置
# 最小化配置，適合快速開始使用

# Lark 應用配置 - 必須填入
lark:
  app_id: "請填入您的Lark App ID"          # 格式：cli_xxxxxxxxxxxxxxxxx
  app_secret: "請填入您的Lark App Secret"  # 從 Lark 開發者後台獲取
  
  # 欄位映射（可依需要調整）
  field_mapping:
    test_case_number: "測試案例編號"
    title: "標題"
    priority: "優先級"
    precondition: "前置條件"
    steps: "測試步驟"
    expected_result: "預期結果"

# 基本處理配置
processing:
  # 測試案例編號格式（依您的專案調整）
  test_case_number_pattern: "^TCG-\\d{3}\\.\\d{3}\\.\\d{3}$"  # TCG-001.002.003
  
  # 批次處理
  batch_processing:
    batch_size: 500
    max_retries: 3

# 日誌配置
logging:
  level: INFO
  file: "logs/conversion.log"

# 使用方式：
# python main.py --config config/quick-start.yaml --xml-file your-file.xml --wiki-token docXXX --table-id tblXXX